export const crepas = [
  {
    id: 1,
    tag: "crepas",
    name: "crepas de Café",
    desc: "Café espresso, leche entera y hielo crepas.",
    price: "$65",
    image: "https://placehold.co/200x200",
  },
  {
    id: 2,
    tag: "crepas",
    name: "crepas Moka",
    desc: "Chocolate oscuro, espresso doble y crema batida.",
    price: "$70",
    image: "https://placehold.co/200x200",
  },
  {
    id: 3,
    tag: "crepas",
    name: "crepas Vainilla",
    desc: "Vainilla natural y leche cremosa.",
    price: "$65",
    image: "https://placehold.co/200x200",
  },
  {
    id: 4,
    tag: "crepas",
    name: "crepas de Fresa",
    desc: "Fresas frescas, leche y un toque especial.",
    price: "$70",
    image: "https://placehold.co/200x200",
  },
  {
    id: 5,
    tag: "crepas",
    name: "crepas Oreo",
    desc: "Galleta Oreo triturada y crema batida.",
    price: "$75",
    image: "https://placehold.co/200x200",
  },
  {
    id: 6,
    tag: "crepas",
    name: "crepas Nutella",
    desc: "Nutella original y leche cremosa.",
    price: "$80",
    image: "https://placehold.co/200x200",
  },
];
