export const eskimos = [
  {
    id: 7,
    tag: "eskimos",
    name: "skimo de Café",
    desc: "Café espresso, leche entera y hielo skimo.",
    price: "$65",
    image: "https://placehold.co/200x200",
  },
  {
    id: 8,
    tag: "eskimos",
    name: "skimo Moka",
    desc: "Chocolate oscuro, espresso doble y crema batida.",
    price: "$70",
    image: "https://placehold.co/200x200",
  },
  {
    id: 9,
    tag: "eskimos",
    name: "skimo Vainilla",
    desc: "Vainilla natural y leche cremosa.",
    price: "$65",
    image: "https://placehold.co/200x200",
  },
  {
    id: 10,
    tag: "eskimos",
    name: "skimo de Fresa",
    desc: "Fresas frescas, leche y un toque especial.",
    price: "$70",
    image: "https://placehold.co/200x200",
  },
  {
    id: 11,
    tag: "eskimos",
    name: "skimo Oreo",
    desc: "Galleta Oreo triturada y crema batida.",
    price: "$75",
    image: "https://placehold.co/200x200",
  },
  {
    id: 12,
    tag: "eskimos",
    name: "skimo Nutella",
    desc: "Nutella original y leche cremosa.",
    price: "$80",
    image: "https://placehold.co/200x200",
  },
];
