export const frappes = [
  {
    id: 13,
    tag: "frappes",
    name: "Frappé de Café",
    desc: "Café espresso, leche entera y hielo frappé.",
    price: "$65",
    image: "https://placehold.co/200x200",
  },
  {
    id: 14,
    tag: "frappes",
    name: "Frappé Moka",
    desc: "Chocolate oscuro, espresso doble y crema batida.",
    price: "$70",
    image: "https://placehold.co/200x200",
  },
  {
    id: 15,
    tag: "frappes",
    name: "Frappé Vainilla",
    desc: "Vainilla natural y leche cremosa.",
    price: "$65",
    image: "https://placehold.co/200x200",
  },
  {
    id: 16,
    tag: "frappes",
    name: "Frappé de Fresa",
    desc: "Fresas frescas, leche y un toque especial.",
    price: "$70",
    image: "https://placehold.co/200x200",
  },
  {
    id: 17,
    tag: "frappes",
    name: "Frappé Oreo",
    desc: "Galleta Oreo triturada y crema batida.",
    price: "$75",
    image: "https://placehold.co/200x200",
  },
  {
    id: 18,
    tag: "frappes",
    name: "Frappé Nutella",
    desc: "Nutella original y leche cremosa.",
    price: "$80",
    image: "https://placehold.co/200x200",
  },
];
