export const waffles = [
  {
    id: 24,
    tag: "waffles",
    name: "Waffle de Café",
    desc: "Café espresso, leche entera y hielo waffle.",
    price: "$65",
    image: "https://placehold.co/200x200",
  },
  {
    id: 25,
    tag: "waffles",
    name: "Waffle Moka",
    desc: "Chocolate oscuro, espresso doble y crema batida.",
    price: "$70",
    image: "https://placehold.co/200x200",
  },
  {
    id: 26,
    tag: "waffles",
    name: "Waffle Vainilla",
    desc: "Vainilla natural y leche cremosa.",
    price: "$65",
    image: "https://placehold.co/200x200",
  },
  {
    id: 27,
    tag: "waffles",
    name: "Waffle de Fresa",
    desc: "Fresas frescas, leche y un toque especial.",
    price: "$70",
    image: "https://placehold.co/200x200",
  },
  {
    id: 28,
    tag: "waffles",
    name: "Waffle Oreo",
    desc: "Galleta Oreo triturada y crema batida.",
    price: "$75",
    image: "https://placehold.co/200x200",
  },
  {
    id: 29,
    tag: "waffles",
    name: "Waffle Nutella",
    desc: "Nutella original y leche cremosa.",
    price: "$80",
    image: "https://placehold.co/200x200",
  },
];
